### ISSUE TITLE
Dlang needs good support for NVidia CUDA programming

### ISSUE THREAD

**Issue by truedat101** [truedat101/dlang-sv-community#24]
Package is: 

http://code.dlang.org/packages/derelict-cuda

Some discussion here:

http://forum.dlang.org/thread/mfnjfc$2lud$1@digitalmars.com?page=1

Once this is done, one could write some samples for CUDA development, and present this at GTC.

**Comment by thewilsonator** [comment]
Solved by http://github.com/libmir/dcompute/

**Comment by truedat101** [comment]
Absolutely!  Happy to close this now.

**Comment by truedat101** [comment]
And thank you @thewilsonator
