### ISSUE TITLE
Dlang needs google protobuf bindings or module

### ISSUE THREAD

**Issue by truedat101** [truedat101/dlang-sv-community#47]
https://github.com/google/protobuf

Yeah, that's sad there is an implementation for PHP but not for D.

**Comment by truedat101** [comment]
🛌

**Comment by acehreli** [comment]
This looks promising: https://code.dlang.org/packages/dproto

**Comment by truedat101** [comment]
@acehreli thank you.  You get a gold 🌟 .  Closing out this issue.
