### ISSUE TITLE
AWS Lambda needs a D runtime

### ISSUE THREAD

**Issue by truedat101** [truedat101/dlang-sv-community#58]
As recently as today, AWS Lambda team made 3 announcements:

1) You can run any language runtime on AWS Lambda.  That was "sort of" always true if you were willing to bundle it up into your code.  But now there is a better way to write the lambda in the native lang.
2) AWS officially supports a Rust runtime for Lambda https://github.com/awslabs/aws-lambda-rust-runtime
3) AWS officially supports a  C++ runtime for lambda

We should look at the above 3 and see how this compares with the existing D package for lambda: https://awslambda-d.readthedocs.io/en/latest/

The things people care about in this regard: 
- how much friction to get started?
- is this natively supported on AWS or not?
- What system overhead (memory, size of lambda zip)?
- Will this be a one off project or can we get it supported by community or at AWS?
- What is the performance downside if any?

**Comment by truedat101** [comment]
Here's more: https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html

The AWS runtime api.

**Comment by jondegenhardt** [comment]
Do you think this might be a candidate for a Google Summer of Code project? See the recent forum message [Google Summer of Code 2019](https://forum.dlang.org/thread/yanpgfffimlauuesqzwy@forum.dlang.org)

**Comment by truedat101** [comment]
This could be pretty good.   I'm thinking that if this gets done, it needs long term support.  It looks like AWS did the C++ version and the Rust version of the runtimes, and there are now a handful of others by third parties.  It would be a good way to elevate the profile of D (keep pace with Go/Rust).  I'm not sure this should wait until the summer.

**Comment by truedat101** [comment]
I haven't scoped the effort here yet.  I also haven't looked at the previous work done for the D-lambda module.

**Comment by jondegenhardt** [comment]
Good point about ongoing support. A Google Summer of Code project might make more sense if there was a mentor committed to long term support.

**Comment by truedat101** [comment]
I haven't quantified if this is a 2 day project, a month long project, a 3 month project, etc.  I suspect it's somewhere between a week and month assuming an experienced lambda developer is involved, and someone who knows D.  Now that there is a clear blueprint in C++ and a clear blueprint in Rust, I think it's a much easier effort to scope.

**Comment by truedat101** [comment]
@jondegenhardt perhaps we can vet the scope of work?  I'll dig into this a bit next week.

**Comment by truedat101** [comment]
Since Lambda has so much traction for these sort of fixed purpose workload tasks, I think it's a big win to get this working.

**Comment by truedat101** [comment]
According to the docs, if we want to implement other languages, we need to implement a Custom Runtime.  Non-custom runtimes are officially supported by AWS.

**Comment by truedat101** [comment]
Wow, it looks like Brainf*** and NIM have lambda layers published: https://github.com/mthenw/awesome-layers

**Comment by truedat101** [comment]
A bunch of these runtimes and layers are here: https://github.com/lambci.

What appears to be true: there isn't much to a runtime: about 60 loc.  There's basically just boilerplate.  How you deploy these things is a bit different than previous approaches with the supported runtimes.  I think I'll just take a stab at the boilerplate.

**Comment by truedat101** [comment]
SSL (or equivalent) appear to be a problem with all of these runtimes.  Most languages don't have a native security stack bundled in the language, but rely on some external OS specific library residing on the host.  Exceptions to this: java, python, node.js, and probably c#.  I suspect this is why they started with these runtimes.  Ditto for libcurl.  This can be a problem for D.  Remains to be determined.

**Comment by truedat101** [comment]
One question I have is about how this actually gets packaged and deployed.  Is it simply that the user builds a binary "app" that is a the Lambda function to push into the cloud, and this gets run on demand, with data being passed into the function via the environment?  I think this is how it works.  Need to read up on it a bit.   Assuming that's true, then the actual lambda is distributable in D as a statically linked app, assuming all shared libraries required that aren't bundled along with the lambda.  It's certainly possible, as I do that with node.js and my lambda that uses native bindings.

**Comment by truedat101** [comment]
Work is being done here: https://github.com/IoTone/Lamb-D/issues/1

**Comment by truedat101** [comment]
I'm about 50% done.

**Comment by truedat101** [comment]
I've got something code complete, working through deployment and packaging issues.  Layers and Runtimes are well documented, AWS style, so dense, and lots to go through.  I will use the C++ code as a model for how to package: https://github.com/awslabs/aws-lambda-cpp#building-and-installing-the-runtime  

It's unfortunate but there are a lot of steps with their C++ code, and that didn't work easily due to cmake use.

**Comment by truedat101** [comment]
So about 90% done, with some packaging and cleanup of the rest of the issue I have open on lamb-D.  Will close this out when I've confirmed working.  This would just get a runtime.  The next project would be to build a lamb-D dlang layer and share that out.  That's a bit more work.

**Comment by ghost91-** [comment]
An alternative on how to package would be static linking or building the binary using same image that is running AWS Lambda. That way we would not need to package the whole libc... see https://github.com/spinscale/crystal-aws-lambda for an example.

**Comment by truedat101** [comment]
@ghost91- yeah, actually that looks like the natural progression.  To get my head around the initial design, I am planning to implement a first cut that works with static linking / packaging the entire thing up, and then improve/iterate.  And the crystal implementation looks complete and the right approach.

**Comment by truedat101** [comment]
Figured out the static linking issue, part of it was getting rid of use of std net curl from the implementation.  Deployed a first cut of this yesterday: http://code.dlang.org/packages/lamb-d

Oddly, someone released a Lambda runtime for D just the day before yesterday : ) !  It is interesting, a translation of the C++ toolkit for Lambda.  http://code.dlang.org/packages/aws-lambda-d

So now there are two implementations, and life is good.

**Comment by truedat101** [comment]
Also, the built package zip is about 2.4mb.  That is smaller than the C++ package produced by the AWS Lambda sdk sample by around 6-7MB.
