### ISSUE TITLE
D needs full standalone AWS SDK bindings

### ISSUE THREAD

**Issue by truedat101** [truedat101/dlang-sv-community#61]
While there exists a vibe-d based library, I fail to understand why we need vibe-d as the core of an AWS SDK.  Outside of devices running in the cloud, we are actually heading in the direction of needing to be more concerned about resource constraints: for IoT and Mobile.  We need more quality libraries that are standalone (zero external dependencies).  Ideally this would be a "from scratch in D" implementation, but honestly, without a major corporate sponsor, that's a huge multi-year task.  As a first step, evaluate wrapping the AWS SDK C or C++ wrappers.  Given the SDK is being modularized, this might be a bit simpler to do on a service by service basis.  Start with the auth library, then go to S3, then EC2, etc.

**Comment by truedat101** [comment]
Related to #58 .  I think we can get the AWS Lambda Layer done without the SDK, but some features won't be easily available with this being done.  Given the performance hit that you take with Lambda when you cold start, a large download that includes everything in Vibe-D + the AWS SDK based on Vibe-D doesn't make sense for use in Lambda.  To make my point stand on solid ground, I need to see what the additional code size is to include dependency on vibe-d.

**Comment by ghost91-** [comment]
There is already existing work on this: https://github.com/Extrawurst/aws-sdk-dlang-gen

**Comment by truedat101** [comment]
@ghost91- this looks fantastic.  I'll give it a spin.
